spring.application.name=EmployeeRecomend
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/emp
spring.datasource.username=3CfGqpbqo7NHGyr.root
spring.datasource.password=mJa4AVkk2cCtqyBi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8090

# ===============================
# REDIS CONFIG
# ===============================
spring.data.redis.url=redis://default:6iTxIHAaQhzgtYlDTerOw7tT4n6pdhY3@redis-18766.c212.ap-south-1-1.ec2.cloud.redislabs.com:18766
# ===============================
# CACHE CONFIG
# ===============================
spring.cache.type=redis

# TTL (Time To Live) = 10 minutes (in milliseconds)
spring.cache.redis.time-to-live=600000

# Rate limiter config
resilience4j.ratelimiter.instances.apiLimiter.limitForPeriod=10
resilience4j.ratelimiter.instances.apiLimiter.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.apiLimiter.timeoutDuration=0

# (Optional monitoring)
management.endpoints.web.exposure.include=*
management.health.ratelimiters.enabled=true